### ISSUE TITLE
審査対応

### ISSUE THREAD

**Issue by tomari** [arigato-java/alexa-javabutton#1]
- [x]  1. 提示されるウエルカムプロンプトは、スキルの説明で定義したスキルの機能の文脈に合ったものにする必要があります。
- [x]  2. ユーザーがスキル内の「ヘルプ」をリクエストした際、スキルはユーザーにスキルのコア機能の操作方法を示すプロンプトを返す必要があります。また、ヘルププロンプトはユーザーへの質問で終わり、もしくは発話を促して終わり、応答を受信するまでセッションを開いたままにしておく必要があります。 ヘルププロンプトの修正をお願いします。
- [x]   3. スキルがタスクを完了した後、ユーザーへのプロンプトが提示されていないにもかかわらずセッションが開いたままになっています。スキルは、リクエストを完了した後、ユーザーの入力を求めるプロンプトを提示していない場合はセッションをクローズする必要があります。セッションを開く場合は、発話を促す言葉で終わるようにしてください。
- [x]  4. 言い回しの異なるサンプル発話が不足しています。スキルを確実に起動させ、多くのユーザーのリクエストに対応するためには、サンプル発話を充実させる必要があります。今回ご提示いただいたサンプル発話のみでは、スキルが確実に起動しない可能性があります。以下のようなサンプル発話を追加して、再度ご申請ください。
- [x]  5. コンパニオンアプリに記載されているサンプルフレーズが、サンプル発話に含まれていません。

```
 1. 提示されるウエルカムプロンプトは、スキルの説明で定義したスキルの機能の文脈に合ったものにする必要があります。
 
再現手順:
ユーザー:アレクサ、ジャバボタンを開いて。
スキル　:あなたとジャバ、今すぐダウンロード。
（（セッションオープン））
 
補足：
ウェルカムプロンプトにスキルの説明を追加してください。またセッションを開く際は必ず発話を促す言葉で終わるよう修正してください。
 
2. ユーザーがスキル内の「ヘルプ」をリクエストした際、スキルはユーザーにスキルのコア機能の操作方法を示すプロンプトを返す必要があります。また、ヘルププロンプトはユーザーへの質問で終わり、もしくは発話を促して終わり、応答を受信するまでセッションを開いたままにしておく必要があります。 ヘルププロンプトの修正をお願いします。
 
再現手順:
ユーザー:アレクサ、ジャバボタンを開いて。
スキル　:あなたとジャバ、今すぐダウンロード。
ユーザー：ヘルプ。
（（セッションクローズ））
 
ヘルプインテントの作成方法については、申請チェックリストのテストケース4.12を参照してください。
 
3. スキルがタスクを完了した後、ユーザーへのプロンプトが提示されていないにもかかわらずセッションが開いたままになっています。スキルは、リクエストを完了した後、ユーザーの入力を求めるプロンプトを提示していない場合はセッションをクローズする必要があります。セッションを開く場合は、発話を促す言葉で終わるようにしてください。
 
再現手順:
ユーザー:アレクサ、ジャバボタンを開いて。
スキル　:あなたとジャバ、今すぐダウンロード。
（（セッションオープン））
 
セッション管理の方法については、申請チェックリストのテストケース4.1を参照してください。
 
4. 言い回しの異なるサンプル発話が不足しています。スキルを確実に起動させ、多くのユーザーのリクエストに対応するためには、サンプル発話を充実させる必要があります。今回ご提示いただいたサンプル発話のみでは、スキルが確実に起動しない可能性があります。以下のようなサンプル発話を追加して、再度ご申請ください。
 
追加例：
JavaKakugenIntent　　名言を教えて
JavaKakugenIntent　　格言を言って
JavaCountIntent　　　デバイスの数は
JavaIntent　　　　　 ジャバして
など
 
サンプル発話の増強について詳しくは、下記のリンク先をご参照ください。
https://developer.amazon.com/ja/docs/custom-skills/best-practices-for-sample-utterances-and-custom-slot-type-values.html
 
5. コンパニオンアプリに記載されているサンプルフレーズが、サンプル発話に含まれていません。
 
該当サンプルフレーズ：
アレクサ、ジャバボタンで名言を言って
アレクサ、ジャバボタンで3回ジャバして
 
以下のサンプル発話を追加してください。
JavaKakugenIntent　　　名言を言って
JavaIntent　　　　　　 {Javacount} 回ジャバして
 
補足：
現在サンプル発話に上記と類似したものがありますが、コンパニオンアプリに記載されるサンプルフレーズは、同じものがサンプル発話に含まれる必要があります。上記の２点の追加をお願いします。
 
サポートされている起動フレーズについて詳しくは、下記のリンク先をご参照ください。
https://developer.amazon.com/ja/docs/custom-skills/understanding-how-users-invoke-custom-skills.html

```

**Comment by tomari** [comment]
というわけですので、ソフト部は各自ご担当箇所の修正をお願いします。

**Comment by tomari** [comment]
争点 「あなたとジャバ　今すぐダウンロード」は広告なのか。ということですが、ここは素直に削除して、どうしても違和感がある場合、あとでサーバサイドでこっそりもとに戻す方針です。

> 
> 1．スキル内でAlexaの音声を使った広告は認められません。広告を削除して、認定を再申請してください。
> 
> 再現手順:
> ユーザー：ジャバ ボタンを開い て
> スキル：あなたとジャバ、今すぐダウンロード
> 
> 補足:
> 「あなたとジャバ、今すぐダウンロード」は java.com/ja/ で表示されている文言ですが、スキル内でこの文言を使用することは、Alexaユーザーに対してJavaをダウンロードするように促進していると捉えられる可能性があるため、広告と判断いたしました。
> 
>  
> 
> 2．ユーザーがスキル内の「ヘルプ」をリクエストした際、スキルはユーザーにスキルのコア機能の操作方法を示すプロンプトを返す必要があります。また、ヘルププロンプトはユーザーへの質問で終わり、もしくは発話を促して終わり、応答を受信するまでセッションを開いたままにしておく必要があります。ヘルププロンプトの修正をお願いします。
> 
> 再現手順:
> ユーザー：ヘルプ
> スキル: ジャバして、と言えば、ジャバと発音します。格言を言って、と言えば、ジャバに関する格言を言います。ジャバが走るデバイスの数を調べて、と言うと、推定デバイス数をお答えします。
> （セッションクローズ）
>

**Comment by tomari** [comment]
サーバ側のログ、200回近く呼び出して、この問題を見つけてきたことがわかります。相当なジャバが、アマゾン社にいることが伺えます。

> 1.  スキル内でAlexaの音声を使った広告及びホームカードを使った広告は認められません。広告を削除して、認定を再申請してください。
> 2.  スキルのホームカードは、スキルの説明で定義したスキルの機能の文脈に合っていません。
> 
> 再現手順：
> ユーザー:アレクサ、ジャバボタンを開いて名言を言って。
> 
> スキル　:ここに関数ジャバ→ノットジャバがあります [atmarkit.co.jp] 。これの不動点を取ることができれば、恐らくそれはジャバ＝ノットジャバを体現するプログラムでしょう。
> 
> 表示されたホームカードの内容 ：
> 
> ここに関数ジャバ→ノットジャバがあります [atmarkit.co.jp] 。これの不動点を取ることができれば、恐らくそれはジャバ＝ノットジャバを体現するプログラムでしょう。
> 
> 問題点：
> 
> [atmarkit.co.jp]。
> 
> ホームカードに提示されたURLがスキルと関連性がありません。削除をお願いします。

**Comment by tobynet** [comment]
占いに近い機能と思われますが、含まれる URL が問題なんでしょうかね。。

**Comment by tomari** [comment]
昨日のパッチで検閲機能入れてるので、当該をリストに入れます。

> １.    スキルに、コンテンツガイドラインに違反するコンテンツが含まれています。コンテンツガイドラインは、こちらから確認できます。 具体的には、大量殺人および/または拷問を含む流血、斬首、および/または過剰な暴力の描写は、Alexaのスキルカタログにはふさわしくありません。 その結果、このスキルの認定を却下しました。
> 
> 該当する応答：
> スキル：ジャバ 殺す 方法
> 
> 補足：
> 「殺す」という表現は過剰な暴力表現であり、不快にとられる可能性があります。当該箇所の削除、または修正をお願いいたします。
> 
>  
> 
> ２.    スキル内でAlexaの音声を使った広告は認められません。広告を削除して、認定を再申請してください。
> 
> 該当する応答：
> スキル：決めたんだ、30億のデバイスで走るのはもうやめにするって 無料Javaのダウンロードから、すべてがはじまる−−−。あなたとJAVA, 今すぐダウンロード
> 
> 補足：
> あなたとジャバ、今すぐダウンロード」は java.com/ja/ で表示されている文言ですが、スキル内でこの文言を使用することは、Alexaユーザーに対してJavaをダウンロードするように促進していると捉えられる可能性があるため、広告と判断いたしました。

**Comment by tomari** [comment]
この指摘は正しくて、実際このスキルを使うと、オラクル社が作っていると誤認する可能性が大いにありました。
修正して、再申請します。

> 1.  Amazon Alexaスキルカタログに申請されたスキルに関して、第三者の商標またはブランドが使用されていたため、認定を却下いたしました。使用されている第三者の商標またはブランド: Oracle Corporation
> 
> 第三者の商標/ブランドが使用されていたメタデータ: スキルの応答
> 
> 補足：スキルの応答に、「welcome to the Oracle」が含まれており、スキルがOracle Corporation公式のスキルであるかのように誤解される可能性がございます。

```
ジャバジャバ～ジャバジャバ～Oh welcome to the Oracle～\nジャバジャバ～ジャババババ～あつまれ神託～
```

**Comment by tobynet** [comment]
直近以外の審査内容、コミット等含めて見ていました。 

事前に聞いていたスキルの品質と異なる、厳しい審査体制が引かれているように見えます。
日本の発売に際して、レギュレーションが厳格になっているのかもしれませんね。

**Comment by tomari** [comment]
@tobynet 西暦2038年、アマゾン政府が独立を宣言して以降、アメリカ大陸東北部ではこのような状況が続いているのです。ここも監視されています。

**Comment by tomari** [comment]
審査通りました. 数々のアドバイス、ありがとうございました。

> おめでとうございます。スキルは認定プロセスに合格し、まもなくスキルストアに公開されます。 
> スキルストアに公開されると、サービスへのトラフィックが増えることが見込まれます。十分なキャパシティがあることをご確認ください。　また、ユーザーが想定外のオペレーションを行なった場合にもサービスが機能し続けることを確認してください。 

https://alexa.amazon.co.jp/spa/index.html#skills/dp/B079Q1DHGL/?ref=&qid=

**Comment by tobynet** [comment]
グッドジャバ！！
