### ISSUE TITLE
Tシャツを受け取りました

### ISSUE THREAD

**Issue by tomari** [arigato-java/alexa-javabutton#2]
ジャバボタンの有用性が認められ、Tシャツをアレクサチームより戴きました。

![alexa_tshirt](https://user-images.githubusercontent.com/1059211/39300577-244b4edc-4987-11e8-8fcd-4a2926f95db2.jpg)

**Comment by tomari** [comment]
ジョーシンでエコーのステッカーを配ってましたので報告します

![alexa_sticker](https://user-images.githubusercontent.com/1059211/39553760-27aab7de-4eaa-11e8-8ff7-a861b688b517.jpg)

**Comment by tobynet** [comment]
It's a cute and cool shape of buttons on the keyboard behind the logo.
