### ISSUE TITLE
マイクロソフト帝国主義から逃れよう

### ISSUE THREAD

**Issue by tomari** [arigato-java/alexa-javabutton#4]
ギットラボに移転先を用意いたしました。リクエスト投げてもらえれば、移転先のアクセス権を設定いたします。
https://gitlab.com/arigato-java/alexa-javabutton

**Comment by tobynet** [comment]
私は必ずしも帝国主義を否定する立ち場にありませんが、試しにギットラボを利用したいと考えています。
私はリクエストのUI が見つけられませんでした、どちらから申請すればよいでしょうか。

2018-6-12 追記: リクエスト了承うけたまわりました。

**Comment by tomari** [comment]
@tobynet ジャバの扉はいつも開かれている

**Comment by tomari** [comment]
私の方で責任を持てそうなものについては、ギットラボに意向して、ギットハブ側のディスクリプションに `(migrated to gitlab)` と移行先URLを記入しました。他のものについては、移行の可否を含めて各担当者でご検討ください。
